<?php require APPROOT . '/View/inc/header.phtml'?>

    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h2 class="text-center">Contact us</h2>
                <h5 class="text-center">Stores</h5>
                <p class="text-center">Vinkovačka 1, 32100 Vinkovci</p>
                <p class="text-center">Osječka 1, 31000 Osijek</p>
                <h5 class="text-center">Customer service</h5>
                <p class="text-center">+1-202-555-0195</p>
                <br>
                <form action="">
                    <div class="form-group">
                        <label for="name">Name: </label>
                        <input type="text" name="name" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="email">Email: </label>
                        <input type="email" name="email" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="subject">Subject: </label>
                        <input type="text" name="name" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="subject">Message: </label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
                    </div>
                    <div class="row">
                        <div class="col text-center" >
                            <input type="submit" value="Send" class="btn btn-success" disabled>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php require APPROOT . '/View/inc/footer.phtml'?>