<?php require APPROOT . '/View/inc/header.phtml'?>

    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h2>Contact us</h2>
                <form action="" method="post">
                    <div class="form-group">
                        <label for="name">Name: </label>
                        <input type="text" name="name" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="email">Email: </label>
                        <input type="email" name="email" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="subject">Subject: </label>
                        <input type="text" name="name" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="subject">Message: </label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="submit" value="Send" class="btn btn-success" >
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php require APPROOT . '/View/inc/footer.phtml'?>