<?php require APPROOT . '/View/inc/header.phtml' ?>
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Webshop</h1>
                <?php flash('register_success'); ?>
                <div class="list-group">
                    <a href="<?= URLROOT ?>/Home/diningRoom" class="list-group-item">Dining Room </a>
                    <a href="<?= URLROOT ?>/Home/garden" class="list-group-item">Garden</a>
                    <a href="<?= URLROOT ?>/Home/livingRoom" class="list-group-item">Living Room</a>
                </div>

            </div>
            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="images/DiningRoom.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="images/Garden.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="images/LivingRoom.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">


                    <?php
                    foreach ($data as $product) {

                        ?>

                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#"><img class="card-img-top"
                                                 src="data:image/jpeg;base64, <?php echo base64_encode($product->product_picture) ?> "
                                                 alt=""></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="Home/productPage/<?=$product->id?>"><?= e($product->product_name) ?></a>
                                    </h4>
                                    <h5>$ <?= e($product->product_price) ?></h5>
                                    <p class="card-text">Product description:</p>
                                    <p class="card-text"><?= e($product->product_description) ?> </p>
                                    <p class="card-text">Product Id: <?= e($product->id) ?> </p>
                                    <?php if (isset($_SESSION['cart'])) : ?>
                                        <div class="col text-center">
                                            <a href="?id=<?= e($product->id) ?> " class="btn btn-outline-success">Add to Cart</a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                    ?>


                </div>
            </div>
        </div>


    </div>


<?php require APPROOT . '/View/inc/footer.phtml' ?>