<?php require APPROOT . '/View/inc/header.phtml' ?>
    <div class="col-md-6 mx-auto">
        <div class="card card-body bg-light mt-5">
            <?php flash('register_success'); ?>
            <h2 class="text-center">New Products</h2>
            <p class="text-center">Check out our newest products.</p>
        </div>
    </div>

    <div class="container my-5">
    <div class="row">
        <?php
        foreach ($data as $product) {

            ?>

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top"
                                     src="data:image/jpeg;base64, <?php echo base64_encode($product->product_picture) ?> "
                                     alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="productPage/<?=$product->id?>"><?= e($product->product_name) ?></a>
                        </h4>
                        <h5>$ <?= e($product->product_price) ?></h5>
                        <p class="card-text">Product description:</p>
                        <p class="card-text"><?= e($product->product_description) ?> </p>
                        <p class="card-text">Product Id: <?= e($product->id) ?> </p>
                        <?php if (isset($_SESSION['cart'])) : ?>
                            <div class="col text-center">
                                <a href="?id=<?= e($product->id) ?> " class="btn btn-outline-success">Add to Cart</a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</div>

<?php require APPROOT . '/View/inc/footer.phtml' ?>