<?php require APPROOT . '/View/inc/header.phtml'?>

    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h2 class="text-center">Change Address</h2>
                <p class="text-center">Please fill out this form to change address.</p>
                <form action="<?php echo URLROOT; ?>/User/changeAddress" method="post">
                    <div class="form-group">
                        <label for="city">City:*</label>
                        <input type="text" name="city" class="form-control form-control-lg
                        <?php echo (!empty($data['cityError'])) ? 'is-invalid' : '';?>" value="<?php echo e($data['city']);?>">
                        <span class="invalid-feedback"> <?php echo $data['cityError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="postalCode">Postal Code:*</label>
                        <input type="number" name="postalCode" class="form-control form-control-lg
                        <?php echo (!empty($data['postalCodeError'])) ? 'is-invalid' : '';?>" value="<?php echo e($data['postalCode']);?>">
                        <span class="invalid-feedback"> <?php echo $data['postalCodeError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="address">Address:*</label>
                        <input type="text" name="address" class="form-control form-control-lg
                        <?php echo (!empty($data['addressError'])) ? 'is-invalid' : '';?>" value="<?php echo e($data['address']);?>">
                        <span class="invalid-feedback"> <?php echo $data['addressError']; ?> </span>
                    </div>
                    <div class="row text-center">
                        <div class="col">
                            <input type="submit" value="Change" class="btn btn-success">
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

<?php require APPROOT . '/View/inc/footer.phtml'?>