<?php require APPROOT . '/View/inc/header.phtml' ?>

    <div class="container">
    <div class="py-5 text-center">

        <h2>Checkout</h2>
    </div>

    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
            </h4>

            <ul class="list-group mb-3">
                <?php foreach ($_SESSION['cart'] as $product): ?>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0"><?= unserialize($product)->product_name ?> </h6>
                        <small class="text-muted">Quantity: <?=unserialize($product)->quantity ?></small>
                    </div>
                    <span class="text-muted">$<?= unserialize($product)->product_price * unserialize($product)->quantity ?></span>
                </li>
                <?php $data['totalPrice'] += unserialize($product)->product_price * unserialize($product)->quantity ?>
                <?php endforeach; ?>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (USD)</span>
                    <strong>$<?=$data['totalPrice']?></strong>
                </li>
            </ul>

        </div>

        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Billing address</h4>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">First name</label>
                    <p><?=$data['customerInfo']->getData('firstname') ?></p>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Last name</label>
                    <p><?=$data['customerInfo']->getData('lastname') ?></p>
                </div>
            </div>

            <div class="mb-3">
                <label for="address">Address</label>
                <p><?=$data['customerInfo']->getData('address') . ' ,'. $data['customerInfo']->getData('postalCode') . ' ' . $data['customerInfo']->getData('city')  ?></p>
            </div>


            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>
            <p>Cash on delivery</p>

            <hr class="mb-4">
            <form action="<?php echo URLROOT; ?>/User/checkout" method="post">
                <?php if(!empty($_SESSION['cart'])) : ?>
                    <input type="submit" name="buy" value="Buy" class="btn btn-success">
                <?php endif; ?>
            </form>

        </div>
    </div>

<?php require APPROOT . '/View/inc/footer.phtml' ?>