<?php require APPROOT . '/View/inc/header.phtml'?>
<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card card-body bg-light mt-5">
            <h2>Login</h2>
            <form action="<?= URLROOT ?>/User/registerSubmit" method="post">
                <div class="form-group">
                    <label for="username">Username: *</label>
                    <input type="text" name="username" class="form-control form-control-lg">
                </div>
                <div class="form-group">
                    <label for="password">Password: *</label>
                    <input type="password" name="password" class="form-control form-control-lg">
                </div>
                <div class="row">
                    <div class="col">
                        <input type="submit" value="Login" class="btn btn-success" btn-block>
                    </div>
                    <div class="col">
                        <a href="<?= URLROOT ?>/User/register" class="btn btn-light btn-block">Don't have an account? Register</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php require APPROOT . '/View/inc/footer.phtml'?>
