<?php require APPROOT . '/View/inc/header.phtml'?>
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h2>Create An Account</h2>
                <p>Please fill out this form to register</p>
                <form action="<?= URLROOT ?>/User/registerSubmit" method="post">
                    <div class="form-group">
                        <label for="email">Email: *</label>
                        <input type="email" name="email" class="form-control form-control-lg">

                    </div>
                    <div class="form-group">
                        <label for="username">Username: *</label>
                        <input type="text" name="username" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="firstName">First name: *</label>
                        <input type="text" name="firstName" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="name">Last name: *</label>
                        <input type="text" name="lastName" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="password">Password: *</label>
                        <input type="password" name="password" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="confirm_password">Confirm password: *</label>
                        <input type="password" name="confirmPassword" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="country">Country: *</label>
                        <input type="text" name="country" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="city">City: *</label>
                        <input type="text" name="city" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="postal_code">Postal code: *</label>
                        <input type="text" name="postalCode" class="form-control form-control-lg">
                    </div>
                    <div class="form-group">
                        <label for="address">Address: *</label>
                        <input type="text" name="address" class="form-control form-control-lg">
                    </div>

                    <div class="row">
                        <div class="col">
                            <input type="submit" value="Register" class="btn btn-success" >
                        </div>
                        <div class="col">
                            <a href="<?= URLROOT ?>/User/login" class="btn btn-light btn-block">Already have an account? Login</a>
                        </div>
                    </div>



                </form>
            </div>
        </div>
    </div>
<?php require APPROOT . '/View/inc/footer.phtml';?>
