<?php require APPROOT . '/View/inc/header.phtml'?>
<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card card-body bg-light mt-5">
            <?php flash('register_success'); ?>
            <h2>Settings</h2>
            <p>Please type and confirm your new password</p>
            <form action="<?php echo URLROOT; ?>/User/settings" method="post">
                <div class="form-group">
                    <label for="password">Password:*</label>
                    <input type="password" name="password" class="form-control form-control-lg
                        <?php echo (!empty($data['passwordError'])) ? 'is-invalid' : '';?>">
                    <span class="invalid-feedback"> <?php echo $data['passwordError']; ?> </span>
                </div>
                <div class="form-group">
                    <label for="confirmPassword">Confirm Password:*</label>
                    <input type="password" name="confirmPassword" class="form-control form-control-lg
                        <?php echo (!empty($data['confirmPasswordError'])) ? 'is-invalid' : '';?>">
                    <span class="invalid-feedback"> <?php echo $data['confirmPasswordError']; ?> </span>
                </div>

                <div class="row">
                    <div class="col">
                        <input type="submit" value="Change" class="btn btn-success">
                    </div>

                </div>

            </form>
        </div>
    </div>
</div>
<?php require APPROOT . '/View/inc/footer.phtml'?>
