<?php require APPROOT . '/View/inc/header.phtml'?>
<div class="card card-body bg-light mt-5">
    <h2 class="text-center">Settings</h2>
    <p class="text-center">Account settings.</p>
    <div class="list-group">
        <a href="<?php echo URLROOT; ?>/User/changePassword" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Change password</h5>
            </div>
            <p class="mb-1">Change your password.</p>
        </a>
        <a href="<?php echo URLROOT; ?>/User/changeAddress" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Change address</h5>
            </div>
            <p class="mb-1">Change your address.</p>
            <small class="text-muted"></small>
        </a>
    </div>
</div>


<?php require APPROOT . '/View/inc/footer.phtml'?>
