<?php require APPROOT . '/View/inc/header.phtml'?>

    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h2 class="text-center">Create Admin</h2>
                <p class="text-center">Please fill this form to add another admin</p>
                <form action="<?php echo URLROOT; ?>/Admin/addAdmin" method="post">
                    <div class="form-group">
                        <label for="email">Email:*</label>
                        <input type="email" name="email" class="form-control form-control-lg
                        <?php echo (!empty($data['emailError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['email'];?>">
                        <span class="invalid-feedback"> <?php echo $data['emailError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="username">Username:*</label>
                        <input type="text" name="username" class="form-control form-control-lg
                        <?php echo (!empty($data['usernameError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['username'];?>">
                        <span class="invalid-feedback"> <?php echo $data['usernameError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="firstName">First Name:*</label>
                        <input type="text" name="firstName" class="form-control form-control-lg
                        <?php echo (!empty($data['firstNameError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['firstName'];?>">
                        <span class="invalid-feedback"> <?php echo $data['firstNameError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="lastName">Last Name:*</label>
                        <input type="text" name="lastName" class="form-control form-control-lg
                        <?php echo (!empty($data['lastNameError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['lastName'];?>">
                        <span class="invalid-feedback"> <?php echo $data['lastNameError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="password">Password:*</label>
                        <input type="password" name="password" class="form-control form-control-lg
                        <?php echo (!empty($data['passwordError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['password'];?>">
                        <span class="invalid-feedback"> <?php echo $data['passwordError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="confirmPassword">Confirm Password:*</label>
                        <input type="password" name="confirmPassword" class="form-control form-control-lg
                        <?php echo (!empty($data['confirmPasswordError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['confirmPassword'];?>">
                        <span class="invalid-feedback"> <?php echo $data['confirmPasswordError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="city">City:*</label>
                        <input type="text" name="city" class="form-control form-control-lg
                        <?php echo (!empty($data['cityError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['city'];?>">
                        <span class="invalid-feedback"> <?php echo $data['cityError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="postalCode">Postal Code:*</label>
                        <input type="number" name="postalCode" class="form-control form-control-lg
                        <?php echo (!empty($data['postalCodeError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['postalCode'];?>">
                        <span class="invalid-feedback"> <?php echo $data['postalCodeError']; ?> </span>
                    </div>
                    <div class="form-group">
                        <label for="address">Address:*</label>
                        <input type="text" name="address" class="form-control form-control-lg
                        <?php echo (!empty($data['addressError'])) ? 'is-invalid' : '';?>" value="<?php echo $data['address'];?>">
                        <span class="invalid-feedback"> <?php echo $data['addressError']; ?> </span>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            <input type="submit" value="Add" class="btn btn-success">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php require APPROOT . '/View/inc/footer.phtml' ?>